image: node:8

pages:
  stage: deploy
  variables:
    REACT_APP_FAKE_API: 1
  script:
  - npm install
  - npm run gulp sass
  - npm run build-fake
  - rm -rf public
  - mv build public
  cache:
    paths:
    - node_modules/
  artifacts:
    paths:
    - public # mandatory, other folder won't work
  only:
  - master