language: node_js
node_js:
  - 8
cache:
  directories:
    - node_modules
env:
  global:
    - PUBLIC_URL=/web
script:
  - npm run gulp sass
  - npm run build-fake

deploy:
  provider: pages
  skip_cleanup: true
  local-dir: build
  github_token: $GITHUB_TOKEN
  on:
    branch: master
